<header>
        <h1>Travelling</h1>
        <nav>
            <ul>
                <li><a>Home</a></li>
                <li><a>Places</a></li>
                <li><a>About</a></li>
            </ul>
        </nav>
    </header>